export const ORDERSTATUS = {
    NEW: 'NUEVO',
    IN_PROGRESS: 'EN PROGRESO',
    PAYED: 'PAGADO',
    SHIPPED: 'ENVIADO',
    CANCELED: 'CANCELADO',
    REFUNDED: 'DEVUELTO'
}
// export const ORDERSTATUS = {
//     NEW: 'NEW',
//     IN_PROGRESS: 'IN PROGRESS',
//     PAYED: 'PAYED',
//     SHIPPED: 'SHIPPED',
//     CANCELED: 'CANCELED',
//     REFUNDED: 'REFUNDED'
// }